#!/bin/bash
set -euo pipefail

#################################
# SYSTEM AWARE OPTIMIZATION
#################################
CORES=$(nproc)
HTTPX_THREADS=$((CORES * 50))
NUCLEI_RATE=$((CORES * 60))

#################################
# CONFIG
#################################
DOMAINS_FILE="domains.txt"
OUT="recon"
SLACK_WEBHOOK="${SLACK_WEBHOOK:-}"

mkdir -p "$OUT"

#################################
# SLACK FUNCTION (PRO TEMPLATE)
#################################
notify() {
  local DOMAIN=$1
  local SUB=$2
  local ALIVE=$3
  local URL=$4
  local FIND=$5

  curl -s -X POST -H 'Content-type: application/json' \
  --data "{
    \"blocks\": [
      {\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\"🧠 Recon Update: $DOMAIN\"}},
      {\"type\":\"section\",\"fields\": [
        {\"type\":\"mrkdwn\",\"text\":\"*New Subdomains*\\n$SUB\"},
        {\"type\":\"mrkdwn\",\"text\":\"*New Alive Hosts*\\n$ALIVE\"},
        {\"type\":\"mrkdwn\",\"text\":\"*New URLs*\\n$URL\"},
        {\"type\":\"mrkdwn\",\"text\":\"*Nuclei Findings*\\n$FIND\"}
      ]}
    ]
  }" "$SLACK_WEBHOOK" > /dev/null
}

#################################
# MAIN LOOP
#################################
while read -r DOMAIN; do
  [[ -z "$DOMAIN" ]] && continue
  [[ "$DOMAIN" =~ ^✔ ]] && continue

  echo "[+] Recon: $DOMAIN"
  D="$OUT/$DOMAIN"
  mkdir -p "$D"

  #################################
  # SUBDOMAIN ENUM (PARALLEL)
  #################################
  {
    subfinder -d "$DOMAIN" -silent &
    assetfinder --subs-only "$DOMAIN" &
    amass enum -passive -norecursive -d "$DOMAIN" &
    wait
  } | sort -u > "$D/subs_today.txt"

  if [[ -f "$D/subs_prev.txt" ]]; then
    comm -13 "$D/subs_prev.txt" "$D/subs_today.txt" > "$D/subs_new.txt"
  else
    cp "$D/subs_today.txt" "$D/subs_new.txt"
  fi
  cp "$D/subs_today.txt" "$D/subs_prev.txt"

  SUB_NEW=$(wc -l < "$D/subs_new.txt" || echo 0)

  #################################
  # ALIVE CHECK (THREADED)
  #################################
  cat "$D/subs_new.txt" \
    | dnsx -silent \
    | httpx -silent -threads "$HTTPX_THREADS" \
    > "$D/alive_today.txt"

  if [[ -f "$D/alive_prev.txt" ]]; then
    comm -13 "$D/alive_prev.txt" "$D/alive_today.txt" > "$D/alive_new.txt"
  else
    cp "$D/alive_today.txt" "$D/alive_new.txt"
  fi
  cp "$D/alive_today.txt" "$D/alive_prev.txt"

  ALIVE_NEW=$(wc -l < "$D/alive_new.txt" || echo 0)

  #################################
  # URL DISCOVERY (PARALLEL)
  #################################
  {
    cat "$D/alive_new.txt" | gau --subs &
    cat "$D/alive_new.txt" | waybackurls &
    wait
  } | sort -u > "$D/urls_today.txt"

  if [[ -f "$D/urls_prev.txt" ]]; then
    comm -13 "$D/urls_prev.txt" "$D/urls_today.txt" > "$D/urls_new.txt"
  else
    cp "$D/urls_today.txt" "$D/urls_new.txt"
  fi
  cp "$D/urls_today.txt" "$D/urls_prev.txt"

  URL_NEW=$(wc -l < "$D/urls_new.txt" || echo 0)

  #################################
  # NUCLEI (DIFF ONLY)
  #################################
  if [[ "$ALIVE_NEW" -gt 0 ]]; then
    nuclei -l "$D/alive_new.txt" \
      -severity medium,high,critical \
      -rate-limit "$NUCLEI_RATE" \
      -o "$D/nuclei_new.txt" || true
  fi

  FINDINGS=$(wc -l < "$D/nuclei_new.txt" || echo 0)

  #################################
  # SLACK ALERT
  #################################
  notify "$DOMAIN" "$SUB_NEW" "$ALIVE_NEW" "$URL_NEW" "$FINDINGS"

  #################################
  # MARK DOMAIN DONE
  #################################
  sed -i "s|^$DOMAIN$|✔ $DOMAIN|" "$DOMAINS_FILE"

done < "$DOMAINS_FILE"

echo "[✓] Recon completed"
